Issue 294
netenglabs/suzieq pull request #461
Opened 2021-11-04 16:08 UTC by LucaNicosia

This is a first version for the resolution of issue 294

2021-11-05 05:25 UTC, ddutt requested changes

2021-11-05 05:25 UTC, ddutt commented on suzieq/poller/services/interfaces.py
> +                entry['speed'] = -1
Vxlan is a virtual interface and its speed SHOULD be 0, not -1.

2021-11-05 05:25 UTC, ddutt commented on suzieq/poller/services/interfaces.py
> +                    entry['speed'] = -1
This is another case where the speed should be 0. These interfaces are loopback interfaces, and are not included in interface assert check.

2021-11-05 16:16 UTC, LucaNicosia commented
[outputcomment.log](https://github.com/netenglabs/suzieq/files/7487410/outputcomment.log)

I attached a yaml file (git doesn't allow me to push it so I renamed it to '.log') with some results of my job.

Please take a look at 'junos' and 'nxos' implementations and even a closer look at "Unlimited" or "auto" speed-value cases for these device types.

Now I start working on tests.

2021-11-10 14:48 UTC, ddutt requested changes

2021-11-10 15:13 UTC, LucaNicosia commented on suzieq/poller/services/interfaces.py
> +        if entry.get('speed',missing_speed_indicator) == missing_speed_indicator:
I think that this function should not be modified.
Take the firewall as an example: there will be a function called `_clean_firewall_data`. Suppose that the firewall replies with `None` if there is no speed. Now in the  `_clean_firewall_data`, we only have to call `_speed_field_check(entry,None)`. Another solution is to check in the  `_clean_firewall_data` body if the speed == None and change it to a -1 and then call `_speed_field_check(entry,-1)` or even directly don't call it.

2021-11-22 14:20 UTC, closed without merging