Add filter by prefix in address and arpnd tables
netenglabs/suzieq pull request #462
Opened 2021-11-05 09:24 UTC by claudiolor

This PR fixes #117 providing a way to filter by the address prefix the records of the `address` and the `arpnd` tables.
The `prefix` parameter has been added in order retrieve all the addresses belonging to the specified subnet:
```
claudio> address show namespace='ospf-single' prefix="10.255.2.0/24"
      namespace   hostname ifname    ipAddressList            macaddr                ip6AddressList state      vrf                        timestamp
0   ospf-single     edge01   eth0  10.255.2.109/24  52:54:00:7e:18:ce                            []    up  default 2021-03-21 19:46:42.916000+01:00
1   ospf-single     exit01   eth0   10.255.2.88/24  52:54:00:ad:87:c3  [fe80::5054:ff:fead:87c3/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
2   ospf-single     exit02   eth0   10.255.2.41/24  52:54:00:bf:13:32  [fe80::5054:ff:febf:1332/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
3   ospf-single   internet   eth0  10.255.2.239/24  52:54:00:e4:b2:74  [fe80::5054:ff:fee4:b274/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
4   ospf-single     leaf01   eth0   10.255.2.23/24  52:54:00:f0:31:4f  [fe80::5054:ff:fef0:314f/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
5   ospf-single     leaf02   eth0  10.255.2.203/24  52:54:00:c9:a9:2a  [fe80::5054:ff:fec9:a92a/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
6   ospf-single     leaf03   eth0  10.255.2.254/24  52:54:00:9b:fd:47  [fe80::5054:ff:fe9b:fd47/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
7   ospf-single     leaf04   eth0   10.255.2.10/24  52:54:00:b5:0b:49   [fe80::5054:ff:feb5:b49/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
8   ospf-single  server101   eth0   10.255.2.78/24  52:54:00:86:a5:9c                            []    up  default 2021-03-21 19:46:42.700000+01:00
9   ospf-single  server102   eth0   10.255.2.68/24  52:54:00:f3:36:56                            []    up  default 2021-03-21 19:46:42.674000+01:00
10  ospf-single  server103   eth0  10.255.2.182/24  52:54:00:8f:f9:5f                            []    up  default 2021-03-21 19:46:42.700000+01:00
11  ospf-single  server104   eth0  10.255.2.219/24  52:54:00:91:59:80                            []    up  default 2021-03-21 19:46:42.700000+01:00
12  ospf-single    spine01   eth0  10.255.2.217/24  52:54:00:a0:1a:f4  [fe80::5054:ff:fea0:1af4/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
13  ospf-single    spine02   eth0   10.255.2.60/24  52:54:00:ae:03:dc   [fe80::5054:ff:feae:3dc/64]    up     mgmt 2021-03-21 19:46:44.640000+01:00
``` 
The `address` parameter keeps its role, which is filtering by an exact IP address:
```
claudio> address show namespace='ospf-single' address="10.255.2.109"
     namespace hostname ifname    ipAddressList            macaddr ip6AddressList state      vrf                        timestamp
0  ospf-single   edge01   eth0  10.255.2.109/24  52:54:00:7e:18:ce             []    up  default 2021-03-21 19:46:42.916000+01:00
```

The following steps should be completed:

- [x] Add `prefix` parameter in `address` table
- [ ] Add `prefix` parameter in `arpnd` table
- [ ] Provide a test suite

2021-11-08 20:18 UTC, LucaNicosia commented on suzieq/engines/pandas/address.py
> +        # Address and prefix filtering are mutual exclusive
I think it is better if you do a test like 
`if len(addr) > 0 and len(prefix) > 0:
  raise error "Cannot use both commands"`

2021-11-08 20:22 UTC, LucaNicosia approved these changes

2021-11-08 20:54 UTC, claudious96 approved these changes

2021-11-09 12:51 UTC, ddutt requested changes

2021-11-09 12:51 UTC, ddutt commented on suzieq/cli/sqcmds/ArpndCmd.py
> +    @argument("prefix",
The text string maybe too long to display well. Have you checked? Alternately, a shorter description might be "Show all addresses in this subnet prefix"

2021-11-09 12:51 UTC, ddutt commented on suzieq/cli/sqcmds/AddressCmd.py
> +    @argument("prefix",
See comment below about how long the help text is and if its an issue.

2021-11-09 12:51 UTC, ddutt commented on suzieq/engines/pandas/address.py
> +        if len(prefix) > 0:
You can do "if prefix", no need to check for length each time, its more pythonic

2021-11-09 12:51 UTC, ddutt commented on suzieq/engines/pandas/address.py
> +        if len(addr) > 0:
Use "if address" instead of len

2021-11-09 12:51 UTC, ddutt commented on suzieq/engines/pandas/address.py
> +        elif len(prefix) > 0:
Change to "elif prefix"

2021-11-09 12:51 UTC, ddutt commented on suzieq/engines/pandas/engineobj.py
> +            PandasObject: A collection of bool reporting the result
Isn't this returning a pd.Series?

2021-11-09 12:51 UTC, ddutt commented on suzieq/engines/pandas/engineobj.py
> +            False if not a else ip_address(a.split("/")[0]) in ip_network(net))
To improve the efficiency of not computing the network each time, can you pull out the ```ip_network(net)``` to be outside this function and pass it the output of ```ip_network(net)``` ?

2021-11-22 14:13 UTC, merged