Add services validation at poller startup
netenglabs/suzieq pull request #481
Opened 2021-11-19 10:59 UTC by claudiolor

At the moment, when users specify the services to execute in the poller with the `-s` flag, or the ones to exclude with the `-x` flag, if one of them is not valid, they are silently ignored. This, for example, could cause some problems with typos:
If a user wants to exclude the `interfaces` services, they could launch:
```sq-poller -D inventory.yml -x interface```
instead of
```sq-poller -D inventory.yml -x interfaces```
Since no error is reported, they won't be aware of the error, until they realises that interfaces are actually polled.

2021-11-19 16:04 UTC, LucaNicosia approved these changes

2021-11-19 16:13 UTC, claudious96 approved these changes

2021-11-22 14:21 UTC, ddutt requested changes

2021-11-22 14:21 UTC, ddutt commented on suzieq/poller/sq_poller.py
> +            print(f'Services {notvalid} excluded, but they '
Why should we continue in this case? For example, if the user typed iterfaces and we continued, that'd be not good, especially if we're not doing so in the case of the other option, "-s". I think you should terminate this as well.

2021-11-23 06:17 UTC, ddutt commented
I'll add a couple of tests to verify these checks work correctly. I'll do them this time. Please add them the next time.

2021-11-23 06:17 UTC, merged