Include panos tests in sqcmds
netenglabs/suzieq pull request #556
Opened 2022-01-11 18:57 UTC by claudious96

This PR enable the discovery of sqcmds for panos as they were not included earlier. It patches some outputs due to fixes applied to the codebase after the tests have been checked in.

2022-01-11 20:00 UTC, LucaNicosia approved these changes

2022-01-11 20:00 UTC, claudiolor approved these changes

2022-01-11 20:56 UTC, ddutt requested changes

2022-01-11 20:56 UTC, ddutt commented on tests/integration/sqcmds/panos-samples/address.yml
>    marks: address show panos filter
For everything in the dual-bgp samples dir, don't we need cumulus in the marks too?

2022-01-12 03:27 UTC, ddutt approved these changes

2022-01-12 03:27 UTC, merged