sq-poller: gracefully terminate with -i mode
netenglabs/suzieq pull request #557
Opened 2022-01-11 20:22 UTC by claudiolor

Currently when the poller is launched with the `-i` flag, it raises an exception when the worker terminates. This PR solves this problem.

2022-01-11 20:57 UTC, ddutt approved these changes

2022-01-11 20:58 UTC, ddutt commented
The one issue with your fix is that we cannot use the run-once=gather output to then be used for run-once=debug. Isn't that right?

2022-01-12 08:36 UTC, LucaNicosia approved these changes

2022-01-12 09:06 UTC, claudious96 approved these changes

2022-01-25 06:27 UTC, ddutt requested changes
I see what you did based on our Slack discussion. But do we need both run-once and single-run-mode the way its coded?

2022-01-25 11:01 UTC, claudiolor commented
> I see what you did based on our Slack discussion. But do we need both run-once and single-run-mode the way its coded?

I think so, because they are different things, `single-run-mode` is an internal variable, which we use inside the controller. We keep `run_once` because we need to pass it as is to the worker. Furthermore, they might assume different values, for example when we launch the controller with the `--debug` flag  and we set `--run-once=update`, `single-run-mode` will be equal to `debug` while `run-once=update` and we need it to show the right command to execute.

2022-01-25 13:37 UTC, merged