Poller worker minor fixes
netenglabs/suzieq pull request #580
Opened 2022-01-26 18:43 UTC by claudiolor

This PR contains some minor fixes for the poller worker:
- Rename the Poller class to Worker
- Allow to pass additional arguments to the Inventory init function

2022-01-27 08:23 UTC, claudious96 approved these changes

2022-01-28 09:29 UTC, LucaNicosia approved these changes

2022-01-30 15:21 UTC, ddutt requested changes
One MUST FIX before commit and the others are just comments or q.

2022-01-30 15:21 UTC, ddutt commented on suzieq/poller/worker/poller.py
> +        inv_types = self._get_inventory_classes()
Whats the motivation to add a new function and change the name?

2022-01-30 15:21 UTC, ddutt commented on suzieq/poller/worker/nodes/node.py
> +                        'the host identity, add "ignore-known-host: True" in '
The keyword is "ignore-known-hosts", not "ignore-known-host".

2022-01-30 19:20 UTC, ddutt commented on suzieq/poller/worker/poller.py
> +        inv_types = self._get_inventory_classes()
Yes, it does, thank you

2022-01-30 20:00 UTC, merged