Sqobject columns cleanup
netenglabs/suzieq pull request #786
Opened 2022-08-19 15:40 UTC by LucaNicosia

## Description

This PR contains some fixes about the columns returned by the sqobject functions:
- empty dataframe columns are now the same as the non empty dataframes (main fix)
- >< filters when using build_query_string function
- add columns filtering to assertions
- change some fields in table schema
- avoid always add 'namespace' field if not in schema (tables doesn't have the namespace field)

### What's left
- [ ] Topology and path tests are failing because I need to craft some ad-hoc tests for them
- [ ] I want to reorganize the commits before merging. I left them in this way to drop them easier if necessary

## Type of change

- Bug fix (non-breaking change which fixes an issue)

2022-08-24 17:16 UTC, ddutt requested changes

2022-08-25 07:49 UTC, LucaNicosia commented on suzieq/engines/pandas/device.py
> +        getcols = list(set(fields + ['timestamp']))
because the addnl_fields are returned as well in the result. The timestamp may not be required, but it's necessary during the parquet read

2022-08-25 07:50 UTC, LucaNicosia commented on suzieq/engines/pandas/address.py
> +            return pd.DataFrame(columns=fields)
I thought about it, but there is no common place to do so unless I do like `summarize` and use a wrapper. I can try this solution

2022-08-25 07:51 UTC, LucaNicosia commented on suzieq/engines/pandas/inventory.py
> +            return pd.DataFrame(columns=fields)
Sqobject is the wrong place because it should be engine agnostic. As I wrote in another comment, I'll try to centralize it.

2022-08-25 08:05 UTC, LucaNicosia commented on suzieq/cli/sqcmds/command.py
> +                                columns=self.columns,
Fixed

2022-08-25 08:07 UTC, LucaNicosia commented on suzieq/engines/pandas/engineobj.py
> +        getcols = list(set(fields + self.schema.key_fields() + [what]))
I do not understand why this must be fixed in sqobject. The engine needs the `what` column even if not present in the `columns` requested by the user. This looks an engine problem to me

2022-08-25 12:11 UTC, ddutt commented on suzieq/engines/pandas/address.py
> +            return pd.DataFrame(columns=fields)
I hear you and I remember. My thought in this case was to create the method now doing just what you're doing. Pass both columns and addnl_fields to the method and it returns pd.DataFrame(cols) or whatever. Later its just a question of modifying the method.

2022-08-25 12:14 UTC, ddutt commented on suzieq/engines/pandas/engineobj.py
> +        getcols = list(set(fields + self.schema.key_fields() + [what]))
No, it is not. Tomorrow, if we add a different engine, then that engine too MUST do the same work. Generally, I prefer single entry common routines such as the ones in sqobject to ensure that engines get the desired fields unless the behavior is specific to the engine itself. In this case, if what is not specified in the columns to be retrieved, every engine we implement needs to add this piece of code. Hope this was clear

2022-08-25 12:15 UTC, ddutt commented on suzieq/engines/pandas/inventory.py
> +            return pd.DataFrame(columns=fields)
sqobjects is engine-agnostic :). I'm  not sure I understand.

2022-09-08 12:24 UTC, LucaNicosia commented on suzieq/engines/pandas/network.py
> +        fields = self.schema.get_display_fields(['default'])
Yes, we use it [here](https://github.com/netenglabs/suzieq/blob/empty-df-cleanup/suzieq/engines/pandas/network.py#L46)

2022-09-08 12:25 UTC, LucaNicosia commented on suzieq/cli/sqcmds/command.py
> +            return self._gen_output(df, dont_strip_cols=True, sort=False)
My bad. Adding it back

2022-09-08 12:38 UTC, LucaNicosia commented on suzieq/engines/pandas/interfaces.py
> +            if_df = pd.DataFrame(columns=self._assert_result_cols)
forgot to remove it. Thanks

2022-09-08 12:41 UTC, LucaNicosia commented on suzieq/engines/pandas/topology.py
> +            return self.lsdb
Where do you see the exception raise?

2022-09-08 12:41 UTC, LucaNicosia commented on suzieq/engines/pandas/tables.py
> +        if ('error' in df.columns) or df.empty:
It's caused by a rebase. I can restore it to the old one

2022-09-08 12:42 UTC, LucaNicosia commented on suzieq/engines/pandas/topology.py
> +            return self.lsdb
I don't understand what is the problem

2022-09-08 12:56 UTC, LucaNicosia commented on suzieq/sqobjects/basicobj.py
> +        """returns an empty dataframe with the input columns
already answered

2022-09-08 12:56 UTC, LucaNicosia commented on suzieq/sqobjects/bgp.py
> +        if fun == 'assert' and columns in [['default'], ['*']]:
Sure. I'll ad the docstring

2022-09-08 13:30 UTC, LucaNicosia commented on tests/integration/test_sqobject_columns.py
> +            pytest.fail(f'{table}.{sq_fun.__name__}({i}) exception (empty): '
I'll add table to pytest.parametrize

2022-09-16 11:29 UTC, ddutt requested changes

2022-09-22 12:45 UTC, merged