Add errDisabled count column to interface summarize
netenglabs/suzieq pull request #894
Opened 2023-05-25 15:10 UTC by AndryNick98

## Related Issue

Fixes #
#879 

## Description

Add errDisabled count column to interface summarize 

## Type of change

- new feature

## Double Check

- [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netenglabs/suzieq/blob/master/CONTRIBUTING.md).
- [x] I have explained my PR according to the information in the comments or in a linked issue.
- [x] My PR source branch is created from the `develop` branch.
- [x] My PR targets the `develop` branch.
- [x] All my commits have `--signoff` applied

2023-05-25 15:49 UTC, claudious96 requested changes

2023-05-25 15:49 UTC, claudious96 commented on suzieq/engines/pandas/interfaces.py
> +            ('errDisabledCnt', 'state == "errDisabled" & adminState == "up"',
Just a minor change, the second string defines a pandas query string (you can read about it [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)). 

As it is in python, `&` is the bitwise `AND` operation, `and` is the boolean `AND` operation instead.

```suggestion
            ('errDisabledCnt', 'state == "errDisabled" and adminState == "up"',
```

2023-05-26 15:06 UTC, LucaNicosia approved these changes

2023-07-15 21:59 UTC, ddutt approved these changes

2023-07-15 21:59 UTC, merged